//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class customerDbEntities : DbContext
    {
        public customerDbEntities()
            : base("name=customerDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerContact> CustomerContacts { get; set; }
        public virtual DbSet<ContractDetail> ContractDetails { get; set; }
        public virtual DbSet<StandardLookup> StandardLookups { get; set; }
        public virtual DbSet<CustomerCounty> CustomerCountys { get; set; }
        public virtual DbSet<Implentat> Implentats { get; set; }
        public virtual DbSet<revenue> revenues { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ProgamType> ProgamTypes { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<CustomField> CustomFields { get; set; }
        public virtual DbSet<AddOn> AddOns { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
    }
}
