//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomField
    {
        public int id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public string FieldValue { get; set; }
        public Nullable<int> FieldType { get; set; }
        public Nullable<bool> boolValue { get; set; }
        public Nullable<decimal> decimalValue { get; set; }
        public string TextValue { get; set; }
        public Nullable<bool> isVisible { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> databaseID { get; set; }
    }
}
