//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomField
    {
        public int id { get; set; }
        public string Field_Name { get; set; }
        public string Field_Value_String { get; set; }
        public Nullable<int> Field_Value_Int { get; set; }
        public Nullable<decimal> Field_Value_Dec { get; set; }
        public string FieldTable { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
