//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Implentat
    {
        public int id { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<int> OldEhr { get; set; }
        public Nullable<decimal> ImplentationFee { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<int> ProjectManager { get; set; }
        public Nullable<int> DataMigrationLead { get; set; }
        public Nullable<int> DataVolume { get; set; }
        public Nullable<bool> Live { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
