//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class revenue
    {
        public int id { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<System.DateTime> PriceFixedUntil { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> Users { get; set; }
        public Nullable<decimal> RevenueAmount { get; set; }
    }
}
