//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDatabas
    {
        public int ID { get; set; }
        public Nullable<int> userId { get; set; }
        public string DatabaseName { get; set; }
        public Nullable<int> databaseID { get; set; }
    }
}
