//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Pasword { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> LoginAttempts { get; set; }
        public string IpAddress { get; set; }
    }
}
